name: Deploy para VPS

on:
  push:
    branches:
      - main   # dispara quando fizer push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar chave SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copiar arquivos para VPS
        run: |
          rsync -avz -e "ssh -p 22376 -o StrictHostKeyChecking=no" ./ \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SERVER_USER }}/meuapp

      - name: Deploy com Docker Compose
        run: |
          ssh -p 22376 -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd /home/${{ secrets.SERVER_USER }}/meuapp &&
            docker compose pull &&
            docker compose up -d --build
          "
